export const planDetails = {
  free: {
    name: "Free",
    price: 0,
    videoLimit: 1,
  },
  basic: {
    name: "Basic",
    price: 19,
    videoLimit: 10,
  },
  pro: {
    name: "Pro",
    price: 49,
    videoLimit: 50,
  },
};

export const Navbaritems = [
  {
    name: "Examples",
    href: "#examples",
  },

  {
    name: "Working",
    href: "#working",
  },

  {
    name: "Features",
    href: "#features",
  },

  {
    name: "FAQ",
    href: "#faq",
  },

  {
    name: "Pricing",
    href: "#pricing",
  },
];

export const FAQitems = [
  {
    question: "What is the AI Shorts Generator?",
    answer:
      "The AI Shorts Generator is a tool that creates short videos automatically from text prompts, designed to simplify the process of content creation for platforms like YouTube Shorts or TikTok.",
  },
  {
    question: "How does the AI Shorts Generator work?",
    answer:
      "Simply input a prompt describing the topic or concept, and the AI will generate a short video based on that. You can then download or remake the video if needed.",
  },
  {
    question: "What types of videos can I create?",
    answer:
      "You can create videos on a wide range of topics, including educational content, entertainment, science facts, and more. The AI adapts to the theme of the prompt you provide.",
  },
  {
    question: "Can I customize the generated shorts?",
    answer:
      "Currently, the AI generates videos based on the prompt with default settings. Future updates will include more customization options.",
  },
  {
    question: "Is there a limit to how many shorts I can generate?",
    answer:
      "There is no limit on the number of shorts you can generate. However, if you plan to generate a large number of videos, please note that it may take some time to process.",
  },
  {
    question: "How long does it take to generate a video?",
    answer:
      "The time it takes to generate a video depends on the complexity of the prompt, but it typically takes a few seconds to a minute.",
  },
  {
    question: "Are the generated videos royalty-free?",
    answer:
      "Yes, all videos generated by our AI Shorts Generator are free for personal or commercial use without any attribution.",
  },
  {
    question: "Can I provide feedback to improve the videos?",
    answer:
      "Yes, we value your feedback! You can reach out to us via our contact form to suggest improvements or report any issues.",
  },
  {
    question: "Is there a cost to use the AI Shorts Generator?",
    answer:
      "Currently, our AI Shorts Generator is free to use. We may introduce premium features in the future for advanced customization options.",
  },
];

export const steps = [
  {
    title: "Choose a Topic",
  },
  {
    title: "Choose a Language",
  },
  {
    title: "Choose a Voice",
  },
  {
    title: "Choose a Duration",
  },
];
